### ISSUE TITLE
Testing and Documentation

### ISSUE THREAD

**Issue by maxrobot** [margined-protocol/perpetuals#18]
Description: Currently testing is substantial, however it is uglier than is desirable.

## Tasks

- [ ]  Think about how we can improve the sexiness of the unit testing
- [ ]  Think about how we can improve the sexiness of the integration testing
- [ ] Think about how we can create maybe a ts|js integration tests using a local network
- [ ] Improve documentation of the code more generally - this may be a new issue but I am just getting the ball rolling wrt to issues.
